spring:
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
    show-sql: true
    open-in-view: false
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/chingubang?characterEncoding=UTF-8&serverTimezone=Asia/Seoul&allowMultiQueries=true&autoReconnection=true&characterEncoding=UTF-8
    username: root
    password: 1234

  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher # Swagger Bug 처리

cors:
  allowed-origins: "*"
  allowed-methods: GET,POST,PUT,PATCH,DELETE,OPTIONS
  allowed-headers: "*"
  max-age: 3600
  apply-url-range: "/**"